SELECT USER_ID,NICKNAME,ADDRESS AS"전체주소",TELNO AS"전화번호"
FROM (
        SELECT 
            B.USER_ID AS USER_ID, 
            B.NICKNAME AS NICKNAME, 
            CONCAT(B.CITY," ",B.STREET_ADDRESS1," ",B.STREET_ADDRESS2) AS ADDRESS, 
            CONCAT(SUBSTR(B.TLNO,1,3),"-",SUBSTR(B.TLNO,4,4),"-",SUBSTR(B.TLNO,8,4)) AS TELNO,
            COUNT(*) AS CNT
      FROM USED_GOODS_USER B INNER JOIN USED_GOODS_BOARD A
      ON B.USER_ID = A.WRITER_ID
      GROUP BY B.USER_ID
      ) USER
WHERE CNT>2
ORDER BY USER_ID DESC